apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: whisper-api
        image: python:3.10
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: test-data
          mountPath: /data

      - name: whisper-stt
        image: whisper
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: test-data
          mountPath: /data

      - name: python-web
        image: python:3.10
        ports:
        - containerPort: 8082
        volumeMounts:
        - name: test-data
          mountPath: /data

      - name: minio
        image: python:3.10
        ports:
        - containerPort: 8083
        - containerPort: 8084
        volumeMounts:
        - name: test-data
          mountPath: /data

      volumes:
      - name: test-data
        hostPath:
          path: /data/test/
          type: Directory


---

apiVersion: v1
kind: Service
metadata:
  name: python
  labels:
    app: python
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: python-0
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: python-1
  selector:
    app: python